### ISSUE TITLE
RGB led strip

### ISSUE THREAD

**Issue by x10iman** [area3001/esp8266_lifx#1]
thank you for this project. did you manage to control a normal RGB led using PWM? just like the origional project.

**Comment by Brubacker** [comment]
We're waiting for some new boards to test this. We'll keep you posted.

**Comment by x10iman** [comment]
Thanks a lot. I played with the cod a bit and connected 3 LEDs with pins 14,12,13 but no output. Serial monitors shows data from the the app but I think setlight() function still needs to be modified if I am no wrong!

**Comment by Brubacker** [comment]
See the branch pwm_rgb for the PWM based RGB led version.
https://github.com/area3001/esp8266_lifx/tree/pwm_rgb
We're also working on a PWM controller RGBW version with selectable color temperature of the white LED 
https://github.com/area3001/esp8266_lifx/tree/pwm_rgbw
